import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { videos } from "@/data/channel";
import { VideoCard } from "@/components/video-card";

export function generateStaticParams() { return videos.map((video) => ({ slug: video.id })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const video = videos.find((item) => item.id === slug); return video ? { title: video.title, description: `Watch ${video.title} from BRAKMASRA.`, openGraph: { type: "video.other", images: [`https://i.ytimg.com/vi/${video.id}/maxresdefault.jpg`] } } : {}; }
export default async function VideoPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const video = videos.find((item) => item.id === slug); if (!video) notFound(); const related = videos.filter((item) => item.id !== video.id).slice(0, 3); const jsonLd = { "@context": "https://schema.org", "@type": "VideoObject", name: video.title, thumbnailUrl: [`https://i.ytimg.com/vi/${video.id}/maxresdefault.jpg`], embedUrl: `https://www.youtube-nocookie.com/embed/${video.id}`, contentUrl: `https://www.youtube.com/watch?v=${video.id}` }; return <div className="page-shell page-top"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /><Link className="text-link" href="/videos"><ArrowLeft />Back to videos</Link><div className="video-player"><iframe src={`https://www.youtube-nocookie.com/embed/${video.id}?rel=0`} title={video.title} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div><div className="video-detail"><span className="eyebrow">BRAKMASRA investigation</span><h1>{video.title}</h1><p>{video.views} · {video.published}</p><a className="button button-primary" href={`https://www.youtube.com/watch?v=${video.id}`} target="_blank" rel="noreferrer">Watch on YouTube <ExternalLink /></a></div><section className="section"><h2 className="subheading">Related encounters</h2><div className="card-grid">{related.map((item) => <VideoCard video={item} key={item.id} />)}</div></section></div>; }
